# Generated by Django 5.2.10 on 2026-02-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, unique=True, verbose_name='Araç Plakası')),
                ('marka_model', models.CharField(max_length=50, verbose_name='Marka ve Model')),
                ('yil', models.IntegerField(verbose_name='Model Yılı')),
                ('guncel_km', models.IntegerField(default=0, verbose_name='Güncel Kilometre')),
                ('durum', models.BooleanField(default=True, verbose_name='Müsait mi?')),
            ],
        ),
        migrations.CreateModel(
            name='SurusKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alis_zamani', models.DateTimeField(auto_now_add=True, verbose_name='Alış Saati')),
                ('alis_km', models.IntegerField(verbose_name='Alış KM')),
                ('alis_fotografi', models.ImageField(blank=True, null=True, upload_to='hasar_fotolari/', verbose_name='Alış Hasar Fotosu')),
                ('teslim_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Saati')),
                ('teslim_km', models.IntegerField(blank=True, null=True, verbose_name='Teslim KM')),
                ('teslim_fotografi', models.ImageField(blank=True, null=True, upload_to='hasar_fotolari/', verbose_name='Teslim Hasar Fotosu')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Sürücü Notları')),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arac_takip.arac', verbose_name='Araç')),
                ('surucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sürücü')),
            ],
        ),
    ]
