# Generated by Django 5.2.10 on 2026-02-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arac_takip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Durak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durak_adi', models.CharField(max_length=100, verbose_name='Durak Adı')),
                ('bolge', models.CharField(max_length=100, verbose_name='Bölge / Semt')),
            ],
        ),
        migrations.AddField(
            model_name='arac',
            name='sahibi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sahip_oldugu_araclar', to=settings.AUTH_USER_MODEL, verbose_name='Araç Sahibi'),
        ),
        migrations.AddField(
            model_name='arac',
            name='bagli_durak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arac_takip.durak', verbose_name='Bağlı Olduğu Durak'),
        ),
    ]
