# Generated by Django 5.2.10 on 2026-02-04 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arac_takip', '0002_durak_arac_sahibi_arac_bagli_durak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arac',
            name='sahibi',
        ),
        migrations.RemoveField(
            model_name='suruskaydi',
            name='alis_fotografi',
        ),
        migrations.RemoveField(
            model_name='suruskaydi',
            name='teslim_fotografi',
        ),
        migrations.AlterField(
            model_name='arac',
            name='bagli_durak',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arac_takip.durak', verbose_name='Bağlı Olduğu Durak'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SurucuProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durak_yoneticisi_mi', models.BooleanField(default=False, verbose_name='Durak Yöneticisi mi?')),
                ('bagli_durak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arac_takip.durak', verbose_name='Bağlı Olduğu Durak')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
