# Generated by Django 5.2.10 on 2026-02-04 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arac_takip', '0003_remove_arac_sahibi_remove_suruskaydi_alis_fotografi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surucuprofili',
            name='durak_yoneticisi_mi',
        ),
        migrations.AddField(
            model_name='durak',
            name='sahibi',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sahip_oldugu_durak', to=settings.AUTH_USER_MODEL, verbose_name='Durak Sahibi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surucuprofili',
            name='onayli',
            field=models.BooleanField(default=False, verbose_name='Patron Onayı Var mı?'),
        ),
        migrations.AddField(
            model_name='surucuprofili',
            name='rol',
            field=models.CharField(choices=[('surucu', 'Sürücü'), ('patron', 'Durak Sahibi')], default='surucu', max_length=10, verbose_name='Kullanıcı Rolü'),
        ),
        migrations.AlterField(
            model_name='surucuprofili',
            name='bagli_durak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arac_takip.durak', verbose_name='Çalıştığı Durak'),
        ),
        migrations.AlterField(
            model_name='suruskaydi',
            name='alis_km',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suruskaydi',
            name='alis_zamani',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suruskaydi',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suruskaydi',
            name='teslim_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suruskaydi',
            name='teslim_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
