# Generated by Django 5.2.10 on 2026-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arac_takip', '0004_remove_surucuprofili_durak_yoneticisi_mi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='sahibi_adi',
            field=models.CharField(default='Durak Malı', max_length=100, verbose_name='Araç Sahibi Adı'),
        ),
        migrations.AddField(
            model_name='arac',
            name='sahibi_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sahip Telefon'),
        ),
    ]
